env: development
debug: true

database:
  url: postgresql+asyncpg://blog_user:bloguserpassword@localhost:5432/blog
  echo: true
  ssl: false

web:

  secret_key: # run: openssl rand -base64 128
  https_only: false

api:
  cors_origins: ""