database:
  database: buyshoes
  user: buyshoes_user
  password: buyshoes_password
  host: 127.0.0.1
  port: 5432
  schema: public

# APP_DB=postgresql://buyshoes_user:buyshoes_password@localhost:5432/buyshoes?sslmode=disable
