from typing import Protocol


class Hasher(Protocol):
    def hash(self, plain: str) -> str: ...

    def verify(self, hashed: str, plain: str) -> bool: ...

    def needs_rehash(self, hashed: str) -> bool: ...

    def dummy_hash(self) -> str: ...


class CredentialRepo(Protocol):
    async def by_email(self, email: str) -> Credential | None: ...

    async def save(self, credential: Credential) -> Credential: ...


class SessionRepo(Protocol):
    async def open(self, *, user_id: int, now: datetime) -> Session: ...

    async def close(self, session_id: str) -> None: ...
